/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package sistemadegestiónderegistros;

import java.awt.Color;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author A.ARMIJOS
 */
public class DetallePelicula extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DetallePelicula.class.getName());
    private Pelicula peliculaEnvio = new Pelicula();
    private Boolean eliminar = false;

    /**
     * Creates new form DetallePelicula1
     */
    public DetallePelicula(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        bEditar.setVisible(false);
        bEliminar.setVisible(false);
        bGuardar.setEnabled(false);
        
        validarCamposListeners();
    }

    public DetallePelicula(java.awt.Frame parent, boolean modal, Pelicula p) {
        super(parent, modal);
        initComponents();
        this.peliculaEnvio = p;
        lTituloVentana.setText(peliculaEnvio.getTitulo());
        tTitulo.setText(peliculaEnvio.getTitulo());
        tDirector.setText(peliculaEnvio.getDirector());
        tAnio.setText(peliculaEnvio.getAnio() + "");
        tDuracion.setText(peliculaEnvio.getDuracion() + "");
        tGenero.setText(peliculaEnvio.getGenero());
        tSinopsis.setText(peliculaEnvio.getSinopsis());
        jImagen.setIcon(new ImageIcon(peliculaEnvio.getPoster()));

        tTitulo.setDisabledTextColor(Color.BLACK);
        tDirector.setDisabledTextColor(Color.BLACK);
        tAnio.setDisabledTextColor(Color.BLACK);
        tDuracion.setDisabledTextColor(Color.BLACK);
        tGenero.setDisabledTextColor(Color.BLACK);
        tSinopsis.setDisabledTextColor(Color.BLACK);

        tTitulo.setEnabled(false);
        tDirector.setEnabled(false);
        tAnio.setEnabled(false);
        tDuracion.setEnabled(false);
        tGenero.setEnabled(false);
        tSinopsis.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tAnio = new javax.swing.JTextField();
        tDuracion = new javax.swing.JTextField();
        tGenero = new javax.swing.JTextField();
        tSinopsis = new javax.swing.JTextField();
        bEditar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bGuardar = new javax.swing.JButton();
        lTituloVentana = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tTitulo = new javax.swing.JTextField();
        tDirector = new javax.swing.JTextField();
        jImagen = new javax.swing.JLabel();
        bCambiarImagen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        bEditar.setText("Editar");
        bEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarActionPerformed(evt);
            }
        });

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        lTituloVentana.setText("Titulo pelicula");

        jLabel2.setText("Título:");

        jLabel3.setText("Director:");

        jLabel4.setText("Año:");

        jLabel5.setText("Duración:");

        jLabel6.setText("Género:");

        jLabel7.setText("Sinopsis:");

        jImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/terminator.jpg"))); // NOI18N
        jImagen.setText("jLabel1");

        bCambiarImagen.setText("Cambiar Imagen");
        bCambiarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCambiarImagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bEliminar)
                        .addGap(125, 125, 125)
                        .addComponent(bEditar)
                        .addGap(18, 18, 18)
                        .addComponent(bGuardar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(38, 38, 38)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(29, 29, 29)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tDirector, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tAnio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(23, 23, 23)
                                    .addComponent(tGenero))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jImagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCambiarImagen, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(lTituloVentana)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTituloVentana)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(bEliminar)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bEditar)
                            .addComponent(bGuardar)
                            .addComponent(bCambiarImagen))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        peliculaEnvio.setTitulo(tTitulo.getText());
        peliculaEnvio.setDirector(tDirector.getText());
        peliculaEnvio.setAnio(Integer.parseInt(tAnio.getText()));
        peliculaEnvio.setDuracion(Integer.parseInt(tDuracion.getText()));
        peliculaEnvio.setGenero(tGenero.getText());
        peliculaEnvio.setSinopsis(tSinopsis.getText());

        this.dispose();
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        eliminar = true;
        this.dispose();
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarActionPerformed
        tTitulo.setEnabled(true);
        tDirector.setEnabled(true);
        tAnio.setEnabled(true);
        tDuracion.setEnabled(true);
        tGenero.setEnabled(true);
        tSinopsis.setEnabled(true);
        
        validarFormulario();
    }//GEN-LAST:event_bEditarActionPerformed

    private void bCambiarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCambiarImagenActionPerformed
        JFileChooser selector = new JFileChooser("./src/resources/");
        selector.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int respuesta = selector.showOpenDialog(this);
        if (respuesta == JFileChooser.APPROVE_OPTION) {
            try {
                peliculaEnvio.setPoster(selector.getSelectedFile().getCanonicalPath());
                
                ImageIcon src = new ImageIcon(selector.getSelectedFile().getCanonicalPath());
                Icon icono = new ImageIcon(src.getImage().getScaledInstance(
                        jImagen.getWidth(), jImagen.getHeight(), java.awt.Image.SCALE_SMOOTH));
                jImagen.setIcon(icono);
                jImagen.setText(null);
            } catch (IOException ex) {
                System.getLogger(DetallePelicula.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
    }//GEN-LAST:event_bCambiarImagenActionPerformed

    public Pelicula getPeliculaEnvio() {
        if (peliculaEnvio != null && !esPeliculaValida(peliculaEnvio)) {
        return null;
    }
        return peliculaEnvio;
    }

    public void setPeliculaEnvio(Pelicula peliculaEnvio) {
        this.peliculaEnvio = peliculaEnvio;
    }

    public Boolean getEliminar() {
        return eliminar;
    }
    
    private void validarCamposListeners() {
        javax.swing.event.DocumentListener validacionListener = new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                validarFormulario();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                validarFormulario();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                validarFormulario();
            }
        };

        // Agregar el listener a todos los campos
        tTitulo.getDocument().addDocumentListener(validacionListener);
        tDirector.getDocument().addDocumentListener(validacionListener);
        tAnio.getDocument().addDocumentListener(validacionListener);
        tDuracion.getDocument().addDocumentListener(validacionListener);
        tGenero.getDocument().addDocumentListener(validacionListener);
        tSinopsis.getDocument().addDocumentListener(validacionListener);
    }

    private void validarFormulario() {
        try {
            // Validar que ningún campo esté vacío
            boolean camposLlenos = !tTitulo.getText().trim().isEmpty() &&
                                   !tDirector.getText().trim().isEmpty() &&
                                   !tAnio.getText().trim().isEmpty() &&
                                   !tDuracion.getText().trim().isEmpty() &&
                                   !tGenero.getText().trim().isEmpty() &&
                                   !tSinopsis.getText().trim().isEmpty();

            if (!camposLlenos) {
                bGuardar.setEnabled(false);
                return;
            }

            // Validar que año y duración sean números válidos
            int anio = Integer.parseInt(tAnio.getText().trim());
            int duracion = Integer.parseInt(tDuracion.getText().trim());

            // Validar rangos
            int anioActual = java.time.Year.now().getValue();
            boolean anioValido = anio >= 1888 && anio <= anioActual;
            boolean duracionValida = duracion > 0 && duracion <= 999;

            // Habilitar botón solo si todo es válido
            bGuardar.setEnabled(anioValido && duracionValida);

        } catch (NumberFormatException e) {
            // Si hay error al parsear, deshabilitar el botón
            bGuardar.setEnabled(false);
        }
    }
    private boolean esPeliculaValida(Pelicula pelicula) {
        if (pelicula == null) return false;

        if (pelicula.getTitulo() == null || 
            pelicula.getTitulo().trim().isEmpty() || 
            pelicula.getTitulo().length() > 50) {
            return false;
        }
        if (pelicula.getDirector() == null || 
            pelicula.getDirector().trim().isEmpty() || 
            pelicula.getDirector().length() > 50) {
            return false;
        }

        // Año: entre 1888 y año actual
        int anioActual = java.time.Year.now().getValue();
        if (pelicula.getAnio() < 1888 || pelicula.getAnio() > anioActual) {
            return false;
        }

        // Duración: entre 1 y 999 minutos
        if (pelicula.getDuracion() <= 0 || pelicula.getDuracion() > 999) {
            return false;
        }
        if (pelicula.getGenero() == null || 
            pelicula.getGenero().trim().isEmpty() || 
            pelicula.getGenero().length() > 50) {
            return false;
        }
        if (pelicula.getSinopsis() == null || 
            pelicula.getSinopsis().trim().isEmpty() || 
            pelicula.getSinopsis().length() > 500) {
            return false;
        }

        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DetallePelicula dialog = new DetallePelicula(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCambiarImagen;
    private javax.swing.JButton bEditar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JLabel jImagen;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lTituloVentana;
    private javax.swing.JTextField tAnio;
    private javax.swing.JTextField tDirector;
    private javax.swing.JTextField tDuracion;
    private javax.swing.JTextField tGenero;
    private javax.swing.JTextField tSinopsis;
    private javax.swing.JTextField tTitulo;
    // End of variables declaration//GEN-END:variables
}
